Repository arduino/uno-r4-wifi-fwuploader-plugin, pull requests merged in 2023-07, with the labels that each got.

#7 Add CI workflow to synchronize with shared repository labels
  .github/workflows/sync-labels.yml
  README.md
Labels: enhancement

#9 Add CI workflow to check Markdown files for problems
  .github/check-markdown-task.yml
  .gitignore
  .markdown-link-check.json
  .markdownlint.yml
  .markdownlintignore
  README.md
  Taskfile.yml
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#10 Add CI workflow to check the license file
  .github/workflows/check-license.yml
  README.md
Labels: type: enhancement, topic: infrastructure

#11 Add CI workflow to validate Taskfiles
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-taskfiles.yml
  README.md
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#12 Add CI workflow to validate GitHub Actions workflows
  .github/workflows/check-workflows-task.yml
  README.md
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#13 revert change committed by mistake
  DistTasks.yml
Labels: type: enhancement, topic: infrastructure

#15 Update README
  README.md
  package-lock.json
Labels: topic: documentation, type: enhancement

#16 Fix contributors link
  README.md
Labels: type: imperfection, topic: documentation, type: enhancement

#17 Update deps
  .licenses/go/github.com/arduino/fwuploader-plugin-helper.dep.yml
  .licenses/go/golang.org/x/exp/constraints.dep.yml
  .licenses/go/golang.org/x/exp/slices.dep.yml
  .licenses/go/golang.org/x/exp/slog.dep.yml
  .licenses/go/golang.org/x/exp/slog/internal.dep.yml
  .licenses/go/golang.org/x/exp/slog/internal/buffer.dep.yml
  go.mod
  go.sum
Labels: topic: code, topic: infrastructure
